### ISSUE TITLE
Teach IOManager and persist() about pathlib.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#867] opened 2017-08-23 01:39 UTC
Under Python 3.6, many standard library functions know to treat `pathlib.Path` objects the same as string paths (e.g. `open()`). Earlier versions do not, and require developers to convert those `pathlib.Path` objects to strings before passing them as arguments.

We can smooth this problem out by immediately coercing all path-like arguments to `PersistenceAgent` and `IOManager` methods (whether passed as strings or `Path` instances) into `Path` instances. This would mean that `persist()` and `IOManager` would use `pathlib` internally for all operations.

Note: We don't even need to coerce the paths back into strings for use with `open()` because `pathlib.Path` provides its own `.open()` method as a file context manager. Additionally, paths referenced in string commands to `subprocess.Popen()` and friends coerce automatically to strings during command formatting: `subprocess.call('lilypond {}'.format(pathlib.Path('foo.ly')))`

**Comment by trevorbaca** [comment] 2017-08-23 21:37
Additionally, `Path.expanduser()` became available in 3.5 (and later) and `Path.glob()` eliminates most cases of `os.listdir()`.

Complete `pathlib` integration is done in the IDE, and everything works. I learned an important lesson about being careful handling `AbjadIDEConfiguration` (which inherits from mainline `AbjadConfiguration`) during `pathlib` integration. No showstoppers, but probably good to be cautious in updating `AbjadConfiguration` while working `pathlib` into `PersistenceAgent` and `IOManager`.

Oh and there are a number of methods on `TestManager` that we can move forward to `pathlib` at the same time as `PersistenceAgent` and `IOManager`.

**Comment by josiah-wolf-oberholtzer** [comment] 2017-08-23 21:48
Curious what you saw with `AbjadConfiguration`. My instinct is to not inherit from it, but instead from the lower-level `Configuration` class, and to just aggregate or delegate to `AbjadConfiguration` when necessary.

**Comment by josiah-wolf-oberholtzer** [comment] 2017-08-23 21:48
Thanks for chipping away at this stuff though!

**Comment by trevorbaca** [comment] 2017-08-23 22:15
Yeah, it was fun to integrate!

The `AbjadIDEConfiguration` drama didn't have to do with with inheritance but rather with the (small but measurable) extra compute-time involved in instantiating `pathlib.Path` objects as compared to the low-level strings produced by `os.path`.

The TL;DR is don't recompute path properties thousands and thousands of times in whatever application you've got ;)

(Details: properties like `AbjadIDEConfiguration.abjad_ide_example_scores_directory` previously returned something like `os.path.join(abjad_ide_directory, 'scores')`. This was fine -- even with bizillions of calls -- because calls to the `os.path` functions are so cheap. But a naive reimplementation as `pathlib.Path(abjad_ide_directory, 'scores')` was computationally expensive enough to affect test run-time noticeably. The solution now in `AbjadIDEConfiguration` is to calculate the `abjad_ide_example_scores_directory` property a single time at initialization and cache it.)

This will only come up for us in `AbjadConfiguration` if we replace `os.path.join()` call with `pathlib.Path()` and then call the resulting property wayyyyy more than we're ever likely to ;)

**Comment by trevorbaca** [comment] 2017-08-23 22:18
Oh, the other (small) lessons learned from IDE integration are these.

1. The `shutil` functions still want string arguments (at least in 3.5).

2. `Path.glob()` can replace basically all `os.listdir()` calls. But note that `Path.glob()` returns full paths (rather than names-only as with `os.listdir()`). Easy change to make but requires doctoring a line or two inside the body of each loop previously headed by `os.listdir()`.

And all the `Path.open()` calls work great out of the box! There are even `Path.read_text()`, `Path.write_text()` methods to read / write in a single line without naming a file pointer explicitly! :)

**Comment by trevorbaca** [comment] 2017-10-06 17:21
Hey @josiah-wolf-oberholtzer, how do you feel about bumping our 3.x requirements all the way up to 3.6?

The `pathlib.Path` methods in 3.6 are amazing. (And we get f-strings with 3.6, too!)

**Comment by trevorbaca** [comment] 2017-10-06 17:27
See also #562.

**Comment by trevorbaca** [comment] 2021-02-17 22:45
Duplicate of #562.

**Closed by trevorbaca** 2021-02-17 22:45 UTC
Labels: refactor
