### ISSUE TITLE
Vanilla installation problems

### ISSUE THREAD

**Issue by eddy-ilg** [Abjad/abjad#878] opened 2017-11-27 23:12 UTC
Hi, 

unfortunately I have problems installing abjad:

apt-get install lilypond
[...]
pip3 install --user abjad 

python3 
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

> >>> import abjad
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/__init__.py", line 27, in <module>
>     from abjad.tools.systemtools.AbjadConfiguration import AbjadConfiguration
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/__init__.py", line 9, in <module>
>     ignored_names=['abjadbooktools'],
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 248, in import_structured_package
>     ignored_names=ignored_names,
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 217, in import_public_names_from_path_into_namespace
>     namespace[element] = __import__(submod, fromlist=['*'])
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/instrumenttools/__init__.py", line 6, in <module>
>     globals(),
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 248, in import_structured_package
>     ignored_names=ignored_names,
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 193, in import_public_names_from_path_into_namespace
>     submodule_name)
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 28, in _get_public_function_names_in_module
>     mod = __import__(module_file, fromlist=['*'])
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/instrumenttools/Percussion.py", line 2, in <module>
>     from abjad.tools import indicatortools
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/indicatortools/__init__.py", line 7, in <module>
>     globals(),
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 248, in import_structured_package
>     ignored_names=ignored_names,
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 193, in import_public_names_from_path_into_namespace
>     submodule_name)
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/systemtools/ImportManager.py", line 28, in _get_public_function_names_in_module
>     mod = __import__(module_file, fromlist=['*'])
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/indicatortools/LaissezVibrer.py", line 5, in <module>
>     class LaissezVibrer(AbjadValueObject):
>   File "/home/eddy/.local/lib/python3.5/site-packages/abjad/tools/indicatortools/LaissezVibrer.py", line 35, in LaissezVibrer
>     _time_orientation = Right
> NameError: name 'Right' is not defined
> >>> 

```

I have no idea, where "Right" should come from. 

Best, 

Eddy

**Comment by josiah-wolf-oberholtzer** [comment] 2017-11-28 02:16
What version of `abjad` did `pip3` install for you?

Run `pip3 freeze` and let me know what the output is.

**Comment by eddy-ilg** [comment] 2017-11-28 08:46
Thanks:

Abjad==2.21
apt-xapian-index==0.47
apturl==0.5.2
beautifulsoup4==4.4.1
blinker==1.3
Brlapi==0.6.4
chardet==2.3.0
checkbox-support==0.22
command-not-found==0.3
cryptography==1.2.3
defer==1.0.6
feedparser==5.1.3
guacamole==0.9.2
html5lib==0.999
httplib2==0.9.1
idna==2.0
Jinja2==2.8
language-selector==0.1
louis==2.6.4
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
oauthlib==1.0.3
onboard==1.2.0
padme==1.1.1
pexpect==4.0.1
Pillow==3.1.2
plainbox==0.25
ply==3.10
ptyprocess==0.5
pyasn1==0.1.9
pycups==1.9.73
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyparsing==2.0.3
python-apt==1.1.0b1
python-debian==0.1.27
python-systemd==231
pyxdg==0.25
reportlab==3.3.0
requests==2.9.1
sessioninstaller==0.0.0
six==1.11.0
system-service==0.3
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.13.1
usb-creator==0.3.0
xdiagnose==3.8.4.1
xkit==0.0.0
XlsxWriter==0.7.3

**Comment by josiah-wolf-oberholtzer** [comment] 2017-11-28 18:08
The `Right` object is defined in Abjad's `abjad/__init__.py` and added to Python's `builtins` namespace. I wonder if it's clashing somehow with one of the other packages you have installed in your Python user packages.

Are you familiar with Python's virtual environments? Would you be willing to set up a virtualenv and only install Abjad into it? I'm curious if it imports properly without the other packages.

Alternatively, there's something strange about your Python installation that's causing the import problem - we test every commit in Travis-CI on multiple versions of Python under Ubuntu, so it does install and work properly in Linux environments.

**Comment by eddy-ilg** [comment] 2017-11-30 09:43
Hi, 

I tested it with virtualenv, but unfortunately there is the same problem:

virtualenv python -p /usr/bin/python3
cd python
bin/pip3 install --user abjad
bin/python3
>>> import abjad
[same error]

bin/pip3 freeze
Abjad==2.21
pkg-resources==0.0.0
ply==3.10
six==1.11.0

The only idea I have is that it could be related to a library file (.so). 

Best, 

Eddy

**Comment by eddy-ilg** [comment] 2017-11-30 11:59
I looked into the code and I don't think its related to my system. The abjad import manager seems to import /lib/python3.5/site-packages/abjad/tools/datastructuretools/OrdinalConstant.py where Right is defined too late, but I am not 100% sure how the import system works.

**Comment by josiah-wolf-oberholtzer** [comment] 2017-11-30 21:11
If you're working in a virtual environment, but Python is importing from the system site packages, that could be a problem.

What Linux distribution are you using? I can't reproduce this in Ubuntu or OSX. Maybe I can spin up a virtual machine and try installing there.

**Comment by psychemedia** [comment] 2017-12-03 17:47
I am getting the same error; it had been working fine in Binderhub but has suddenly stopped working?

https://mybinder.org/v2/gh/psychemedia/showntell/music?filepath=index_music_abjadBROKEN.ipynb

Buildfile here: https://github.com/psychemedia/showntell/tree/music

**Comment by josiah-wolf-oberholtzer** [comment] 2017-12-03 20:58
@psychemedia Can you tell me:

- what version of Abjad you're using?
- what OS and OS version you're running it under?

I need to know because I can't reproduce this problem with Abjad 2.21 under OSX or Ubuntu.

**Comment by psychemedia** [comment] 2017-12-03 21:05
Linux 4.9.49-moby x86_64, Abjad==2.21

You can see it break in this [live example notebook](https://mybinder.org/v2/gh/psychemedia/showntell/music?filepath=index_music_abjadBROKEN.ipynb).

**Comment by josiah-wolf-oberholtzer** [comment] 2017-12-03 21:20
@psychemedia I'm a little lost. The live notebook example seems to work fine. Abjad imports, I can reference `Right`. The notebook even generates LilyPond output somehow. What exactly is broken?

Did you experience the OP's problem with `Right` on your local machine?

**Comment by psychemedia** [comment] 2017-12-03 23:04
Hmm... yes... it's working in that latest build for me now too. 

It had stopped working in an earlier build on both Binderhub and locally.

I had noticed in the build there was a lot of Linux package updates going on - I wonder if one of those caused something to go out of sync?

**Comment by trevorbaca** [comment] 2018-10-28 21:52
Appears that no problem remains in thread. Closing.

**Closed by trevorbaca** 2018-10-28 21:52 UTC
