### ISSUE TITLE
Tune Abjad to read-only filesystems

### ISSUE THREAD

**Issue by AlmogCohen** [Abjad/abjad#521] opened 2015-09-28 10:56 UTC
Currently I've started working with abjad to generate some very cool thing I will show you all in the future :)

Anyway, everything goes great when working on my PC. Then when I tried loading my app into AWS elasticbeanstalk server the problems start. For some reason abjad insist on writing configuration files onto the hard disk. All I want to do is create lilypond representation of some score.

On AWS EB the file system is read-only so I'm unable to use abjad there. 
Is there anyway to fix this? or to go around the non-needed configuration files?

The trackback:

```
mod_wsgi (pid=5053): Exception occurred processing WSGI script '/opt/python/current/app/application.py'.
Traceback (most recent call last):
  File "/opt/python/current/app/cool_app/algo.py", line 7, in <module>
    from abjad import *
  File "/opt/python/run/venv/lib/python2.7/site-packages/abjad/__init__.py", line 31, in <module>
    abjad_configuration = AbjadConfiguration()
  File "/opt/python/run/venv/lib/python2.7/site-packages/abjad/tools/systemtools/AbjadConfiguration.py", line 51, in __init__
    Configuration.__init__(self)
  File "/opt/python/run/venv/lib/python2.7/site-packages/abjad/tools/systemtools/Configuration.py", line 27, in __init__
    os.makedirs(self.configuration_directory)
  File "/opt/python/run/baselinenv/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/opt/python/run/baselinenv/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/wsgi'
```

**Comment by AlmogCohen** [comment] 2015-09-28 11:00
I'm not too familiar with abjad source-code but I feel that the best way to solve this is to make the Configuration persistence optional. If writing to the disk is not possible the Configuration should have default values. If the filesystem is accessible the configuration should be saved. What do you think?

**Comment by josiah-wolf-oberholtzer** [comment] 2015-09-28 17:00
Hi Almog. I was wondering when this question would finally appear! I'm sympathetic to your request, and am happy to look into a fix. This will affect not only the configuration system, but also our parsers, which are based on [PLY](https://github.com/dabeaz/ply). They currently write out parser tables to the file system.

To make the changes, I first need to set-up a test environment in Travis-CI that mimics some of the read-only aspects of AWS. Can you tell me (as someone who has not worked with AWS yet): can you install *anything* there (even via a package manager like APT)? I want to know if I can remove some test dependencies. There are quite a lot of tests that write to the file system, so I need to locate them all and apply the appropriate skip decorators for a read-only environment.

**Comment by josiah-wolf-oberholtzer** [comment] 2015-09-28 18:59
I've made some progress. Abjad no longer fails if its configuration file can't be written to disk.

One large problem remains: Abjad's LilyPondParser.

Normally, the LilyPond parser constructs its parser tables and write them out to disk in ```~/.abjad/parsers```. This saves it from having to re-construct them every time any LilyPond string needs to be parsed, as the grammar is rather large, and building the tables is not trivial. Normally, parser table construction happens at most once, on initial import of Abjad. If the tables do not exist on disk, each new instantiation of the LilyPond parser will be forced to reconstruct the tables. We don't use a single global parser because I don't believe PLY's parser framework is thread-safe, and I don't want to forbid the possibility of multiple threads working on Abjad at once (for example, in a web server). Right now, my Travis-CI tests are effectively blocked for the read-only environment because they spend all of their time rebuilding the parser tables.

In your AWS EB environment, there's not even the possibility of temporary directories? Can you set your home directory to ```/tmp```?

**Comment by gkthiruvathukal** [comment] 2015-09-28 20:19
I wonder whether you could achieve what yuu want to do w/o any changes to Abjad. I've done a lot of work using FUSE (in my own research) and came along this interesting project, nullfs, which would essentially write everything to /dev/null. It would be interesting to see whether this breaks anything!

This thread seems to present a similar use case:
http://unix.stackexchange.com/questions/9332/how-can-i-create-a-dev-null-like-blackhole-directory

In sum, FUSE is about being able to mount a filesystem in userland. So this means, no special privileges required. Then you could just mount the nullfs and "store" the configuration there. Because it's /dev/null, of course, you'd be able to write files just file but there'd be nothing there when a corresponding read is done of the configuration.

**Comment by josiah-wolf-oberholtzer** [comment] 2015-09-28 20:28
By "store" you do mean "go irretrievably into a blackhole", right?

I think the configuration-problem is solved. We just don't write them, and
everything works fine.

The problem is that we use a PLY-based parser with a huge grammar that
expects to be able to pickle and unpickle its parser tables. And we use
this parser in basically every single test and doctest. If it can't write
out its parser tables and read them back in, it will re-construct them
every single time, which is basically all of the time in our test suite.

Now, with the changes I've already made today, this situation may suffice
for Almog's purposes. But if I can't get the test suite to finish under
Travis, I can't guarantee that it will continue to work under read-only
environments.

**Comment by AlmogCohen** [comment] 2015-09-29 07:00
My jaw actually dropped to the floor when reading your responses! I'm so glad for your fast response and fix. It even more awesome using abjad now that I see how devoted the creator is to its creation :)

I'll find the time soon to look into the problems you mentioned about the tests for read-only enviroments and try to help solve these problems too.

For your questions:
1.
> In your AWS EB environment, there's not even the possibility of temporary directories? Can you set your home directory to /tmp?

When deploying to AWS EB my website is served over nginx, I dont think I want to mess with the local home dir (moving it to /tmp or something).
Anyway the whole machine is temporary! I use nothing local when uploading my website to the Elastic Beanstalk. My DB in on another server and all the code is uploaded once the server is created. Each time I deploy a new version of my app the server is restarting, and sometimes it is built new from the ground. So there is not much use for the configuration persistency anyway. I assume writing to /tmp is a possibility, how do you intend to use it?

2.
> Can you tell me (as someone who has not worked with AWS yet): can you install anything there (even via a package manager like APT)?

As mentioned here in the link I provide below, the supported package managers are currently: yum, rubygems, python, and rpm - [Packages Documentation](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#customize-containers-format-packages)

**Comment by AlmogCohen** [comment] 2015-09-29 11:28
I have another bug which I almost sure came from the no-configuration stuff
I sent to lilypond a file from abjed (version installed by pip directly from the github project)
Its header was like:
```
% 2015-09-29 11:21
\\version ""
\\language "english"
\n    #(define bars-per-line 4)\n\n    
```

And as a punishment I got this error:
```
error: file too old: 0.0.0 (oldest supported: 2.7.38)
```
What do you think?
Can you explain again what is the problem with the read-only tests? How could I help to solve it?

**Comment by josiah-wolf-oberholtzer** [comment] 2015-09-29 16:12
1) I keep asking about being able to write to disk, as this will Abjad to write its parser tables, even temporarily. In googling, it seems that some people who need to write out temporary files, for whatever reason, set their home directory to /tmp on AWS EB. If you intent on doing a lot of processing, there's a good chance you'll use the parser - even without realising it, as it is pervasive in Abjad. So finding a solution to the parser table pickle-file problem is crucial. It's also important that I get a solution to this because it guarantees that I can run the test suite in a read-only environment. If I can't run the test suite in each target environment (or pretty close), then I can't support that environment; it will likely break in the future. If you can write to disk somehow, then this becomes a moot-point for me.

2) Thanks for the package manager info - that means I don't need to modify my Travis-CI configuration much.

3) You should install LilyPond on your AWS EB instance. It's available on most Linux package managers, or you can wget an installer from their website. Abjad uses LilyPond's version string (```lilypond -v```) to dynamically determine what version to fill into the ```\version "???"``` directive. If you compile a LilyPond file with a missing or faulty ```\version``` directive, it will complain, as you can see.

**Comment by AlmogCohen** [comment] 2015-10-01 07:14
Ok, I've checked and as predicted I have complete write permissions to the tmp folder, should I check anything else?

**Comment by josiah-wolf-oberholtzer** [comment] 2015-10-01 16:05
Yes! That's great news. I'll work on a /tmp/-based parser-table cache.

In the meantime, could you check if its possible to set your home directory
to /tmp/? I know that's a little ridiculous, but it seems to be a technique
people use to get around read-only environments. It would obviate any
changes I need to do.

**Comment by AlmogCohen** [comment] 2015-10-06 08:34
Hi but I'd prefer to not change my home directory...My app is quite complex and I cant change such things in order to support one package.

Is it not better to write to the temp folder when necessary?

**Comment by josiah-wolf-oberholtzer** [comment] 2017-07-10 05:36
Not clear if this still matters. Closing.

**Closed by josiah-wolf-oberholtzer** 2017-07-10 05:36 UTC
Labels: refactor
